### PR TITLE
Fixes #73. MDCTabBarScroller creates own instance of MDCTabBar.

### LINKED ISSUE #73: MDCTabBarScroller creates own instance of MDCTabBar.
### What RMWC Version are you using?

> Master at 353e4d40c6be518297ff6f9056b4f75f8f2a6785

### What browser(s) and React Version is this bug affecting?

> All

### What build system are you using?

> Webpack

### What are the steps to reproduce the bug?

> Wrap TabBar in TabBarScroller. Click on tabs.  Examine devtools console for errors.

I've submitted a PR for this one.

### PR DESCRIPTION
**Pull request by vdkdev**
Fixes #73.

A foundation instance (MDCTabBar) must be passed from MDCTabBarScroller to the enclosed TabBar component.

The TabBar component will check if it's contained within TabBarScroller by searching for 'mdc-tab-bar-scroller' class up the hierarchy. If detected TabBar will create a dummy MDCComponent instance during construction. The second instance of MDCTabBar created by MDCTabBarScroller will replace the dummy instance through the apiRef hook (provided by withTabBarApi hoc) in TabBar::onUpdate.

### CODE REVIEW

**Comment by jamesmfriedman** [comment]
@vdkdev Thanks for all of the activity around Tab bars!

This particular PR really breaks Reacts DOM abstraction by using the querySelector methods and traversing dom nodes.

I think I understand what the issue is, the TabBar scroller and the Tab bar are "disconnected" and a dummy one is being instantiated in its place. I think there might be a much easier way to handle this, either by using Reacts context api, or by passing the scroll bar instance directly in.

Mind if I take a look at this? I starting doing a bit of cleanup from your last couple of PRs, mostly just matching naming conventions, making sure the pieces were documented, and correcting some minor Flow typing issues.

Other than that, your work has been stellar and appreciated.

**Comment by vdkdev** [comment]
Absolutely. The proposed solution deserves a second look.

**Comment by vdkdev** [comment]
@jamesmfriedman I've updated the PR to make it easier for you to refactor it. DOM traversal hacks are gone. The context is used to pass the required properties from TabBarScroller to TabBar. 

The TabBarScroller component is now being properly reinitialized when tabs change. 

Finally, there is a new "with TabScroller" checkbox on the TabBar story form to test "dynamic" tabs in different scenarios.

And thanks for the kind words!

**Comment by jamesmfriedman** [comment]
@vdkdev I just pushed to the V1 branch which corrects this issue without the DOM workarounds. Take a look and let me know what you think.

**Comment by jamesmfriedman** [comment]
@vdkdev please take a look at #88 if you get a chance.

**Comment by jamesmfriedman** [comment]
You also might want to merge in / look at https://github.com/jamesmfriedman/rmwc/pull/97 which fixes the active tab issue.

**Comment by jamesmfriedman** [comment]
@vdkdev I went through your code and ported it over to #97 with a few modifications. Please take a look and verify it's working as expected.

Also, would you like to be an official collaborator? You definitely seem to have the most understanding of whats going on, and you've already helped fix some really epic issue.

Is ok it we close this one out in favor of #97?

**Comment by vdkdev** [comment]
@jamesmfriedman  I've tried adding a dynamic tab with TabScroller as a parent and the component becomes disconnected (activeTabIndex stops updating in the TabBar story).  I haven't had a chance to take a closer look.

I'm okay with moving it all to #97.

You can count me in! I'll try to help as much as can.

**Comment by jamesmfriedman** [comment]
Closing this in favor of #97

**Pull request closed without merging**
