### PR TITLE
Fix data driven Select shown value

### PR DESCRIPTION
**Pull request by MiK546**
After upgrading RMWC to 8.0.0 I noticed that all enhanced Select menus in my application changed to show the value instead of the label of their selected option. I decided to debug this a bit and ended up finding that the foundation of the component is setting the shown text to the value (instead of the label) for some reason in a `useEffect` function. I made a small change to that function and now the text is instead fetched using the index of the selected option and the `adapter.getMenuItemTextAtIndex()` method. I hope this is an acceptable fix, at least it didn't seem to cause any additional problems.

I attempted to make a test for this regression but didn't manage to make enzyme fire the `useEffect()` for some reason and eventually gave up. As the situation wasn't tested before either, I hope the test missing is not a problem.

### CODE REVIEW

**Comment by EmiBemi** [comment]
Thank you for taking the time to make a pull request! I noticed this as well in our projects when bumping to RMWC v8. I will have a look at this right away.

**Review by EmiBemi — DISMISSED** [review]
Tested locally and it seems to be working

**Comment by b-d-m-p** [comment]
@EmiBemi Is this dependency met locally?

```
 Could not resolve dependency:
npm ERR! peer react@"^16.0.0-0" from enzyme-adapter-react-16@1.15.6
npm ERR! node_modules/enzyme-adapter-react-16
npm ERR!   dev enzyme-adapter-react-16@"^1.15.6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.0.0-0" from enzyme-adapter-react-16@1.15.6
npm ERR!   node_modules/enzyme-adapter-react-16
npm ERR!     dev enzyme-adapter-react-16@"^1.15.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-06-16T14_22_52_334Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by b-d-m-p** [comment]
@EmiBemi Maybe we should use this unofficial React 17 Enzyme adaptor https://www.npmjs.com/package/@wojtekmaj/enzyme-adapter-react-17

**Review by EmiBemi — APPROVED** [review]

**Pull request merged**
