### PR TITLE
Bump MWC to version 6

### PR DESCRIPTION
**Pull request by EmiBemi**
MWC has now been updated to version 6.

- All existing components should be working (breaking changes has been fixed).
- Added a todo.md file to list all features/components that needs to be added.
- All tests are succeeding, expect slider-ssr tests as MWC introduced a breaking change for server-side rendering. This change is fixed in V7. A comments regarding this issue has been added to the test file.

To test this PR:
Setup:

npm install
npm run pretest
Things to validate

Run the docs: npm start
Run storybook: npm run storybook
Run the test suite: npm test

### CODE REVIEW

**Review by thaestrup — APPROVED** [review]
Review comments are located in Nykredit repo.

**Comment by EmiBemi** [comment]
@thaestrup @jamesmfriedman  Merge conflicts should now be resolved for this PR.

**Review by thaestrup — APPROVED** [review]

**Comment by jamesmfriedman** [comment]
Thanks @EmiBemi! I added a `next` branch for us to use for doing version updates and have target that as the head_ref for this PR.

**Review by jamesmfriedman — APPROVED** [review]
Looks good! 

For all future PRs (now that you're a collaborator) lets do them with branches inside the RMWC repository instead of forks.

**Comment by EmiBemi** [comment]
@jamesmfriedman Right, sure thing!

**Pull request merged**
