### PR TITLE
Removing contribution verbiage

### PR DESCRIPTION
**Pull request by jamesmfriedman**
- Removes references to contribution verbiage throughout
- Replaces image of my face on docs page with RMWC icon 
- Can't "Shut down" open collective without losing existing list of backers. Hid all of the contribution information on the profile page, updated the text , and removed all tiers.

### CODE REVIEW

**Review by thaestrup — APPROVED** [review]

**Review by EmiBemi — APPROVED** [review]

**Comment by b-d-m-p** [comment]
Should we leave it to James to merge it or should we just merge if approved?

**Comment by EmiBemi** [comment]
Let's just merge it! Do you want the honor @b-d-m-p ? :)

**Comment by b-d-m-p** [comment]
Ok! 😃

**Comment by jamesmfriedman** [comment]
No need to wait for me on stuff guys, you're all officially maintainers now ;)

**Pull request merged**
