### PR TITLE
fix(drawer): list items don't show name and icon in story

### PR DESCRIPTION
**Pull request by j-o-d-o**
Change to the correct key `displayName` and add the icon as `<ListItemStartDetail>`

### CODE REVIEW

**Comment by jamesmfriedman** [comment]
curious @j-o-d-o, are you able to merge after an approved review? Not sure how this works on public repos.

**Comment by j-o-d-o** [comment]
Nope, it says only users with write access can merge pull requests.

**Comment by jamesmfriedman** [comment]
Speaking of which, any interest in #80?

**Comment by jamesmfriedman** [comment]
Ah, just saw your comment!

**Pull request merged**
