### PR TITLE
MDC 31

### PR DESCRIPTION
**Pull request by jamesmfriedman**
This one was uncharacteristically easy. #150

### CODE REVIEW

**Comment by jamesmfriedman** [comment]
That seems like a good thing to add programmatically. Maybe make a wrapper component with that logic and then pass it to a ChipIconRoot?

**Comment by j-o-d-o** [comment]
Sounds like a plan. Yet, the user should still be able to not use tabindex and role.

**Comment by j-o-d-o** [comment]
But I guess we can also merge this right now and publish and keep that extension in mind for the future.

**Comment by jamesmfriedman** [comment]
Thanks @j-o-d-o. I'll get this merged and deployed. Nice to have an easy week :).

**Pull request merged**
