### PR TITLE
Version 1

### PR DESCRIPTION
**Pull request by GideonFlynn**
Everything seems to work as it should. No broken links and great examples. Props also seem to work as expected although I haven't tested them thoroughly.
___

- [x] Add a 'dark' card to the card docs and instructions on how to apply the dark theme correctly.
- [x] Removed the link to the Icon docs as the page doesn't exist.

### CODE REVIEW

**Comment by jamesmfriedman** [comment]
Hi @GideonFlynn, it looks like you have the old version of the codebase. Maybe you accidentally looked at the rmwc/master branch instead of rmwc/V1?

**Comment by GideonFlynn** [comment]
Yeah, I'm new to the whole contributing and merging PR's thing. I had the new version but something went wrong, then i reset everything, forked your repo, copy pasted the files and commit messages and instantly made PR in my excitement.

**Comment by jamesmfriedman** [comment]
No worries, after you fork, just `git checkout V1` and that should be looking at the V1 code which is what needs to be reviewed.

**Comment by GideonFlynn** [comment]
I opened a new PR because I was unable to reopen this :expressionless:. Thank you for the help and understanding.

**Pull request closed without merging**
