### PR TITLE
FIx console.log in Select.

### PR DESCRIPTION
**Pull request by izakfilmalter**

### CODE REVIEW

**Comment by jamesmfriedman** [comment]
Thanks for catching this, its not actually meant to even be in there anymore, was just debugging, but I'll merge this in and remove it later.

**Comment by izakfilmalter** [comment]
Ya I keep getting an error so idk.

**Comment by jamesmfriedman** [comment]
I'm pretty sure it's related to a timing issue with MDC and the virtual DOM. it's hard to know when to call resize, so it's easier to just call it everytime and catch the error. As soon as I stop logging it, you won't see it anymore.

**Comment by izakfilmalter** [comment]
Ya I'm fairly sure this triggers when the view gets destroyed and it trys
to update it self.

**Pull request merged**
