### PR TITLE
Adding testing for multiple versions of React

### PR DESCRIPTION
**Pull request by jamesmfriedman**
This was pretty hard. Found an epic workaround for doing multi-version react testing.

Steps to tests the "tests"

- pull the repo
- npm i
- npm test
- npm run test:watch

### CODE REVIEW

**Comment by jamesmfriedman** [comment]
@j-o-d-o I don't know if you get notifications when you get assigned, but check this out if you get a chance

**Comment by jamesmfriedman** [comment]
Also slipping in Selects with non-floating labels. I realized they changed the way they were handling this and we didn't the ability to replicate them in RMWC.

**Comment by jamesmfriedman** [comment]
Thanks @ginavasiloff

**Comment by j-o-d-o** [comment]
2549 changed files with +521,933 added lines : D. It's cause npm doesn't allow to have multiple versions of the same package? Maybe switching to yarn in the future could be an option?

To be fair, I am not super familiar with jest. But it seems to work!

**Comment by jamesmfriedman** [comment]
@j-o-d-o Just that little comment made me want to go back and improve :). Modified this to use a pretest script to do the installation so no more tracking of react in the repo. Thanks for the nudge. In the meantime, I seem to have destroyed this branch trying to amend the git history, so I'm going to open a new PR.

**Pull request closed without merging**
