### PR TITLE
use prettier#main

### PR DESCRIPTION
**Pull request by gugu**

### CODE REVIEW

**Comment by gugu** [comment]
btw do we still need to use git dependency? I bet they released a new version since that change

**Comment by gugu** [comment]
@jamesmfriedman without this PR development version does not start

**Review by amadsen — COMMENTED** [review]
@jamesmfriedman It looks like the github dependency on prettier was added in November 2019 - possibly to pick up what were then unpublished changes. I'm considering approving this PR to allow the dev version to build, then opening a new PR to use the latest version published on npm. Thoughts?

**Comment by jamesmfriedman** [comment]
This is resolved by #740, going to close this in favor of that.

**Pull request closed without merging**
