### PR TITLE
fix(TabBar): activeTabIndex doesn't set active tab of 0 on load #94

### PR DESCRIPTION
**Pull request by jamesmfriedman**
@izakfilmalter You were really close, thanks for looking into it. If you can pull this branch and validate I'll publish a quick patch.

### CODE REVIEW

**Comment by jamesmfriedman** [comment]
@vdkdev I think this PR will fix the issues we've been talking about. Can you pull this branch and verify? I'm adding you as a collaborator so feel free to pull the branch and push back to this PR.

**Comment by jesnil01** [comment]
Just tested this out and it seems to work!

**Comment by jamesmfriedman** [comment]
Thanks @jesnil01. @vdkdev Just waiting for your acknowledgement on this one before I merge.

**Comment by jamesmfriedman** [comment]
Of course @vdkdev!

**Comment by jamesmfriedman** [comment]
I'm not gonna lie @vdkdev, you're a wizard. This ended up being one of the most complex issues I've seen so far. It would have been so easy if MDC just treated them as separate components.

Anyways, validated it works, thanks for your help on this one! Going to merge and release a patch.

**Comment by vdkdev** [comment]
I couldn't agree more. The lack of separation between the underlying components is the root of the problem.
Your work around this issue helped immensely. Cheers!

**Pull request merged**
