### PR TITLE
feat(List): selectedIndex && a11y enhancements

### LINKED ISSUE #554: List HandleSelection
Converting over from the defunct Material-Components-Web-React which has a [`singleSelection`](https://github.com/material-components/material-components-web-react/tree/master/packages/list#single-selection) property on Lists making it easy to pass the selected index of a list back up my app with the `handleSelect` wizardry.

Anything similar in RMWC or do I have to hard code an `onClick` for each list item?

### PR DESCRIPTION
**Pull request by mgr34**
Hi @jamesmfriedman , 

here is that PR I promised the other week. Sorry about the delay--*Work stuff* :)

The weekend allowed me time to reflect. I think your suggestion to remove `singleSelection` was wise. The other variants are not so explicit in their naming. This meshes with the library.  However, the branch name is a bit funky now ;)

You can properly determine `singleSelection` from `selectedIndex: number[] | number` and some queries. Only checkbox expects `number[]`--Switch too, if it wasn't for the mdc-foundation throwing an error. if number and is radioList than role should be set to `radiogroup`. Finally, if a selectedIndex is present, and the other checks fail than we can safely say we have a singleSelection. We can tell the foundation to set it, and set the role to listbox. 

this would close #554 with the reccomendtation you use `onAction={ evt => handleSelect(evt.detail.index)}`

### CODE REVIEW

**Comment by jamesmfriedman** [comment]
Love this Matt. Haven't had time to review just yet, but plan on getting it in. Might chat you up on discord about it some more. Also, would you like to be added to this repo as an official contributor?

**Comment by mgr34** [comment]
>Might chat you up on discord about it some more.

Sounds good. 

> Also, would you like to be added to this repo as an official contributor?

Sure, I don't see any reason not to be. My contributions might not always be as regular, but as I continue to use this project and MDC continues to make breaking changes I'm likely to find things that I *need* to implement. :)

**Comment by jamesmfriedman** [comment]
Haven't forgotten about this, just still triaging issues as they're popping up. Want to get this out for a 6.1 release.

**Comment by mgr34** [comment]
Hi @jamesmfriedman  thanks for checking in. I noticed the CHANGELOG the other day. Bug fixes should take priority. Hopefully you'll find time soon, but no rush.

**Comment by mgr34** [comment]
Hey @jamesmfriedman I suspect you're busy lately, but I was wondering if you still plan to review this PR. I note that it did not make it in for the 6.1 release as planned.

**Comment by jamesmfriedman** [comment]
You know @mgr34 extremely busy, but the good news is that I'll be devoting quite a bit of time to RMWC coming up, so this is not forgotten.

**Comment by mgr34** [comment]
For a busy man you respond awfully quick ;) 
But hey, I've been busy as well. Thanks for following up. I just wanted to check in as its been a couple months. No rush.

**Comment by jamesmfriedman** [comment]
@mgr34 if you can fix the conflicts I'll get this in

**Comment by mgr34** [comment]
Thanks @jamesmfriedman. I'll try to wrap this up shortly/by the end of the week. Need to finish up another project first.

**Comment by mgr34** [comment]
@jamesmfriedman On second thought I was able to take care of that quickly. It should be good to go.

Thanks again.

**Comment by jamesmfriedman** [comment]
Did not forget about this, definitely still going to make it in with the next release.

**Comment by mgr34** [comment]
Thanks for checking in @jamesmfriedman. I understand you have a lot going on at the moment. Don't feel too much pressure.

**Pull request closed without merging**
