### PR TITLE
Version 1

### PR DESCRIPTION
**Pull request by jamesmfriedman**
After a ton of freaking work, it looks like RMWC is ready for an official V1. I'm adding anyone that has expressed interest or has commited something in the past. Please pull down the V1 branch, and verify the following.

- clone branch
- cd rmwc
- npm i
- npm start, navigate to localhost:3000
- poke around the docs and verify things are working as expected
- npm test, verify the tests are working and passing
- Leave feedback, and review anything you can!

@jrajav
@j-o-d-o 
@alexeyraspopov
@vdkdev
@izakfilmalter
@UFOMelkor

### CODE REVIEW

**Comment by j-o-d-o** [comment]
Wow man, its a lot of stuff! Awesome! 
I looked through the code and did some testing. LGTM! 

I would wait through the weekend, maybe more feedback is coming.

**Comment by jamesmfriedman** [comment]
Thanks for the PR @GideonFlynn. I updated the example a bit, but good call adding an explicit dark mode section.

**Comment by ginavasiloff** [comment]
All of the built-in tests passed. I also didn't see any issues with how the components are working when I built and ran this branch. Nice work!

**Comment by jrajav** [comment]
Browsed over most of the commits - all looks fine. Just one question, why was material-components-web updated to 0.28.0 at some point (currently the latest version) but then switched back to 0.27.0?

**Comment by jamesmfriedman** [comment]
Not sure what you mean @jrajav, I just double checked the version on the V1 branch is 28 and on master it's 27. Thanks for checking out the PR!

**Comment by jrajav** [comment]
Yep, just realized my mistake - I was looking at master very puzzled. All good!

**Comment by GideonFlynn** [comment]
I forgot to mention that all tests passed while on this branch.

Im excited that I'm not the only one with all green, go version 1! :smile:

**Comment by GideonFlynn** [comment]
I forgot to mention that all tests passed while on this branch.

Im excited that I'm not the only one with all green, go version 1

**Comment by jamesmfriedman** [comment]
Thanks for the feedback everyone. In the future, releases will be much smaller, was just a big push on documentation and bugfixing. I'm going to get this released :)

**Pull request merged**
